apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresdatabases.postgrespilot.io
spec:
  group: postgrespilot.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                databaseName:
                  type: string
  scope: Namespaced
  names:
    plural: postgresdatabases
    singular: postgresdatabase
    kind: PostgresqlDatabase
    shortNames:
      - psql
